variables:
  IMAGE: rigetti/lisp

docker-tag:
  image: docker:stable
  tags:
    - dockerd
    - github
  before_script:
    - docker -v
    # needed for executing the Makefile
    - apk add make
    - echo ${IMAGE}
    - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
  after_script:
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep ${IMAGE})
  # matches only on tags of the form YYYY-MM-DD
  only:
    refs:
      - /^(\d\d\d\d)-(\d\d)-(\d\d)$/
  except:
    refs:
      - branches
  variables:
    LATEST: ${IMAGE}:latest
  script:
    - eval VERSION=$(cat VERSION-QUICKLISP.txt)
    # make sure tag matches VERSION-QUICKLISP.txt
    - if [ "${CI_COMMIT_TAG}" = "${VERSION}" ]; then RELEASE=${IMAGE}:${VERSION}; else return 1; fi
    - make
    - docker tag ${RELEASE} ${LATEST}
    - docker push ${RELEASE} && docker push ${LATEST}
